### ISSUE TITLE
Copied text from any web page containing <table> is pasted as raw HTML

### ISSUE THREAD

**Issue by mr-mig** [github/paste-markdown#21]
The change for converting `<table>` to markdown has introduced an unexpected side-effect: any text copied from a webpage containing `<table>` inside is pasted as raw HTML.

This caused a couple of identified issues in Dotcom already: 
1. https://github.com/github/issues/issues/1804
1. https://github.com/github/issues/issues/1902
1. https://github.com/github/github/issues/184107

There are possible workarounds for specific places (as described [here](https://github.com/github/issues/issues/1804#issuecomment-865024173) for example), but the generic solution is needed.

Here's a gif with repro: 
<details>

1. Text, selected by double-click (single word) can be pasted as-is without problems.
2. A selection resulting from single-click + drag over the comment text will be pasted as raw HTML

![Kapture 2021-06-21 at 15 22 15](https://user-images.githubusercontent.com/1062491/122769148-f7e32b00-d2ac-11eb-9928-74a707169606.gif)
</details>

**Comment by koddsson** [comment]
Fixed in [0.3.3](https://github.com/github/paste-markdown/releases/tag/v0.3.3).
