### ISSUE TITLE
Pasting HTML with links can place link in the wrong place

### ISSUE THREAD

**Issue by jclem** [github/paste-markdown#45]
When pasting HTML such as this:

example [example](https://example.com)

...the link will end up at the wrong place in the pasted Markdown. This appears to be because we [search the `text/plain` clipboard content for the first occurrence of the linked string](https://github.com/github/paste-markdown/blob/14eb3b2eb9758e15af5049060e82bc86ba478115/src/paste-markdown-html.ts#L73). This is a reasonable heuristic, but ends up with edge cases like the one above.

I'm not sure what the right solution here is, but since we have a document returned by a `DOMParser`, anyway, perhaps we could instead generate Markdown by using `NodeIterator` or `TreeWalker`?

**Comment by imjohnbo** [comment]
I missed this one coming through @jclem – thanks, you're right. We'll take a look.
